DROP FUNCTION IF EXISTS AlbumTotalDuration;

DELIMITER $$

CREATE FUNCTION AlbumTotalDuration(IdAlbum INT)
RETURNS VARCHAR(5)
BEGIN
DECLARE Seconds INT UNSIGNED;
SELECT SUM(s.Duration) INTO Seconds FROM Song s WHERE s.IdAlbum = IdAlbum;
RETURN CONCAT(FLOOR(Seconds / 60), ':', (Seconds % 60));
END $$

DELIMITER ;