SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `Errori`;
DROP TABLE IF EXISTS `Album`;
DROP TABLE IF EXISTS `Brani`;
DROP TABLE IF EXISTS `Utenti`;
DROP TABLE IF EXISTS `Seguaci`;
DROP TABLE IF EXISTS `Iscrizioni`;
DROP TABLE IF EXISTS `Collezioni`;
DROP TABLE IF EXISTS `BraniCollezione`;
DROP TABLE IF EXISTS `Playlist`;
DROP TABLE IF EXISTS `BraniPlaylist`;
DROP TABLE IF EXISTS `Code`;
DROP TABLE IF EXISTS `Ascoltate`;
DROP TABLE IF EXISTS `Login`;

-- Table di supporto Errori
CREATE TABLE IF NOT EXISTS `Errori` (
    `Errore` VARCHAR(256) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=Latin1;
-- Table Album
CREATE TABLE IF NOT EXISTS `Album` (
	`IdAlbum` INT(11) NOT NULL AUTO_INCREMENT,
	`Titolo` VARCHAR(200) NOT NULL,
	`Autore` VARCHAR(200) NOT NULL,
	`Info` VARCHAR(300) DEFAULT NULL,
	`Anno` YEAR DEFAULT NULL,
	`Live` BOOLEAN DEFAULT FALSE,
	`Locazione` VARCHAR(100) DEFAULT NULL,
    `PathCopertina` VARCHAR(100) NOT NULL DEFAULT "img/covers/nocover.jpg",
	PRIMARY KEY(`IdAlbum`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Brani
CREATE TABLE IF NOT EXISTS `Brani` (
	`IdBrano` INT(11) NOT NULL AUTO_INCREMENT,
	`IdAlbum` INT(11) NOT NULL,
	`Titolo` VARCHAR(200) NOT NULL,
	`Genere` VARCHAR(40) NOT NULL,
	`Durata` INT(11),
	PRIMARY KEY(`IdBrano`),
	FOREIGN KEY(`IdAlbum`) REFERENCES Album(`IdAlbum`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Utenti
CREATE TABLE IF NOT EXISTS `Utenti` (
	`IdUtente` INT(11) NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(40) DEFAULT NULL,
	`Cognome` VARCHAR(40) DEFAULT NULL,
	`Email` VARCHAR(40) NOT NULL,
	PRIMARY KEY(`IdUtente`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Login
CREATE TABLE IF NOT EXISTS `Login` (
    `Username` VARCHAR(40) NOT NULL,
	`Password` VARCHAR(40) NOT NULL,
    `Amministratore` BOOLEAN DEFAULT FALSE,
    `IdUtente` INT(11) NOT NULL,
    PRIMARY KEY(`Username`),
    FOREIGN KEY(`IdUtente`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Seguaci
CREATE TABLE IF NOT EXISTS `Seguaci` (
	`IdUtente` INT(11) NOT NULL,
	`IdSeguace` INT(11) NOT NULL,
	CONSTRAINT PRIMARY KEY pk(`IdUtente`, `IdSeguace`),
	FOREIGN KEY(`IdUtente`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`IdSeguace`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE,
	CHECK(`IdUtente` != `IdSeguace`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Iscrizioni
CREATE TABLE IF NOT EXISTS `Iscrizioni` (
	`IdUtente` INT(10) NOT NULL,
	`Tipo` ENUM('Free', 'Premium') NOT NULL,
	PRIMARY KEY(`IdUtente`),
	FOREIGN KEY(`IdUtente`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Collezioni
CREATE TABLE IF NOT EXISTS `Collezioni` (
	`IdCollezione` INT(11) NOT NULL AUTO_INCREMENT,
	`IdUtente` INT(11) NOT NULL,
	PRIMARY KEY(`IdCollezione`),
	FOREIGN KEY(`IdUtente`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table BraniCollezione
CREATE TABLE IF NOT EXISTS `BraniCollezione` (
	`IdBrano` INT(11) NOT NULL,
	`IdCollezione` INT(11) NOT NULL,
	CONSTRAINT PRIMARY KEY pk(`IdCollezione`, `IdBrano`),
	FOREIGN KEY(`IdBrano`) REFERENCES Brani(`IdBrano`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`IdCollezione`) REFERENCES Collezioni(`IdCollezione`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Playlist
CREATE TABLE IF NOT EXISTS `Playlist` (
	`IdPlaylist` INT(11) NOT NULL AUTO_INCREMENT,
	`IdUtente` INT(11) NOT NULL,
	`Nome` VARCHAR(40) NOT NULL,
    `Privata` BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(`IdPlaylist`),
	FOREIGN KEY(`IdUtente`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table BraniPlaylist
CREATE TABLE IF NOT EXISTS `BraniPlaylist` (
	`IdPlaylist` INT(11) NOT NULL,
	`IdBrano` INT(11) NOT NULL,
    `Posizione` INT(11) NOT NULL,
	CONSTRAINT PRIMARY KEY pk(`IdPlaylist`, `IdBrano`),
	FOREIGN KEY(`IdPlaylist`) REFERENCES Playlist(`IdPlaylist`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`IdBrano`) REFERENCES Brani(`IdBrano`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Code
CREATE TABLE IF NOT EXISTS `Code` (
	`IdUtente` INT(11) NOT NULL,
	`IdBrano` INT(11) NOT NULL,
    `Posizione` INT(11) NOT NULL,
	CONSTRAINT PRIMARY KEY pk(`IdUtente`, `IdBrano`, `Posizione`),
	FOREIGN KEY(`IdUtente`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`IdBrano`) REFERENCES Brani(`IdBrano`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Table Ascoltate
CREATE TABLE IF NOT EXISTS `Ascoltate` (
	`IdUtente` INT(11) NOT NULL,
	`IdBrano` INT(11) NOT NULL,
	`Timestamp` TIMESTAMP NOT NULL,
	CONSTRAINT PRIMARY KEY pk(`IdUtente`, `IdBrano`, `Timestamp`),
	FOREIGN KEY(`IdUtente`) REFERENCES Utenti(`IdUtente`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`IdBrano`) REFERENCES Brani(`IdBrano`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;
